services:
  jekyll:
    build:
      context: .
      dockerfile: Dockerfile.jekyll
    container_name: jekyll-blog
    ports:
      - "4000:4000"
    volumes:
      - .:/srv/jekyll:cached
    environment:
      - JEKYLL_ENV=development

